<a href="https://colab.research.google.com/github/mainarel/Numerical_methods_7/blob/main/Lab1_Gauss_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Решение СЛАУ методом Гаусса**

# Стандартный метод Гаусса:

Заполнение матрицы:

In [109]:
import numpy as np
import matplotlib.pyplot as plt
import sys

# размер матрицы А - n x n, B - n x 1
n = 4

# A = np.array([[1.0,10.0,3.0],[3.0,2.0,1.0],[4.0,5.0,6.0]])
# B = np.array([[3.0,4.0,7.0]]).reshape(n,1)
#A = np.random.randint(1, 100, (n, n))
A = np.random.rand(n, n)
print('Матрица А: \n', A)


#B = np.random.randint(1, 100, (n, 1))
B = np.random.rand(n, 1)
print('Матрица B: \n', B)

X = np.zeros(n)

AM = np.column_stack((A, B[:, 0]))
print('Расширенная матрица А: \n', AM)

Матрица А: 
 [[0.21752338 0.52488309 0.91524365 0.54375054]
 [0.78729617 0.43026723 0.00512375 0.62206772]
 [0.2074201  0.16200388 0.78484008 0.63896278]
 [0.97785587 0.28213396 0.36553768 0.74835227]]
Матрица B: 
 [[0.713179  ]
 [0.67732313]
 [0.1907246 ]
 [0.66153691]]
Расширенная матрица А: 
 [[0.21752338 0.52488309 0.91524365 0.54375054 0.713179  ]
 [0.78729617 0.43026723 0.00512375 0.62206772 0.67732313]
 [0.2074201  0.16200388 0.78484008 0.63896278 0.1907246 ]
 [0.97785587 0.28213396 0.36553768 0.74835227 0.66153691]]


Приведение к треугольному виду:

In [99]:
def triangle_form(expanded_matrix):
  for i in range(n):
      if expanded_matrix[i][i] == 0.0:
          sys.exit('Divide by zero')
          
      for j in range(i+1, n):
          main = expanded_matrix[j][i]/AM[i][i]
          
          for k in range(n+1):
              expanded_matrix[j][k] = expanded_matrix[j][k] - main * expanded_matrix[i][k]
  print('Полученная треугольная матрица: \n', expanded_matrix)
  return expanded_matrix
    
  

Обратная подстановка:

In [108]:
def back_substitution(xi, matrix):
  xi[n-1] = matrix[n-1][n]/matrix[n-1][n-1]

  for i in range(n-2,-1,-1):
      xi[i] = matrix[i][n]
      
      for j in range(i+1,n):
          xi[i] = xi[i] - matrix[i][j]*xi[j]
      
      xi[i] = xi[i]/matrix[i][i]
  return xi

In [93]:
def solution(expanded_matrix, xi, mod):
  if (mod == 0):
    tr_m = triangle_form(expanded_matrix)
  else:
    tr_m = triangle_form_mod(expanded_matrix)

  array = back_substitution(xi,tr_m)
  return array

In [101]:
from scipy.linalg import solve
x_real = solve(A, B).reshape(1,n)
print('Истинное решение:  \n', x_real)
print(solution(AM, X, 0))
err = abs(x_real-X)
print('Ошибка \n ', err)

Истинное решение:  
 [[ 2.35858177 -0.03248533 -1.53461187  0.82300279]]
Полученная треугольная матрица: 
 [[ 3.09706576e-01  3.17756172e-01  3.38548266e-02  3.82609658e-01
   9.83080669e-01]
 [ 0.00000000e+00  2.57559939e-01  6.88599421e-01 -3.76594271e-01
  -1.37503790e+00]
 [ 0.00000000e+00  0.00000000e+00  1.53938854e+00 -5.71968214e-01
  -2.83309537e+00]
 [-5.55111512e-17  0.00000000e+00  0.00000000e+00 -5.58306272e-01
  -4.59487622e-01]]
Полученное решение:  [ 2.35858177 -0.03248533 -1.53461187  0.82300279]
[ 2.35858177 -0.03248533 -1.53461187  0.82300279]
Ошибка 
  [[8.88178420e-16 4.51028104e-16 4.44089210e-16 1.11022302e-16]]


# Метод с выбором главого элемента

Приведение к треугольному виду:

Функция перестановки строк:

In [110]:
def swap(matrix, index_from_line, index_to_line):
  line1, line2 = np.copy(matrix[index_from_line, :]), np.copy(matrix[index_to_line, :])
  matrix[index_to_line, :] = line1
  matrix[index_from_line, :] = line2
  return matrix

In [111]:
def triangle_form_mod(expanded_matrix):
  for i in range(n):
      if (expanded_matrix[i][i] == 0.0): 
          sys.exit('Divide by zero')

      if  expanded_matrix[i][i] != abs(max(expanded_matrix[i:, i])):
        index_line = np.argmax(abs(expanded_matrix[i:,i])) + i
        swap(expanded_matrix, index_line, i) 

      for j in range(i+1, n):
          main = expanded_matrix[j][i]/expanded_matrix[i][i]
          for k in range(n+1):
              expanded_matrix[j][k] = expanded_matrix[j][k] - main * expanded_matrix[i][k]
    
  print('Полученная треугольная матрица: \n', AM)
  return expanded_matrix


In [112]:
from scipy.linalg import solve
x_real = solve(A, B).reshape(1,n)
print('Истинное решение:  \n', x_real)
print(solution(AM, X, 1))
err = abs(x_real-X)
print('Ошибка \n ', err)

Истинное решение:  
 [[ 0.66311857  1.17139753  0.28431218 -0.56299063]]
Полученная треугольная матрица: 
 [[ 0.97785587  0.28213396  0.36553768  0.74835227  0.66153691]
 [ 0.          0.46212258  0.83393004  0.37728009  0.56602056]
 [ 0.          0.          0.52295179  0.39682152 -0.07472524]
 [ 0.          0.          0.          0.35128851 -0.19777214]]
[ 0.66311857  1.17139753  0.28431218 -0.56299063]
Ошибка 
  [[2.22044605e-16 0.00000000e+00 1.11022302e-16 3.33066907e-16]]
