<a href="https://colab.research.google.com/github/mainarel/Numerical_methods_7/blob/main/Lab1_Gauss_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Решение СЛАУ методом Гаусса**

Заполнение матрицы:

In [102]:
import numpy as np
import matplotlib.pyplot as plt
import sys
from scipy.linalg import solve

# размер матрицы А - n x n, B - n x 1
n = 5

#A = np.array([[1.0,10.0,6.0],[3.0,2.0,1.0],[4.0,10.0,6.0]])
#B = np.array([[3.0,19.0,7.0]]).reshape(n,1)
#A = np.random.randint(1, 100, (n, n))
A = np.random.rand(n, n) * 10
print('Матрица А: \n', A)


#B = np.random.randint(1, 100, (n, 1))
B = np.random.rand(n, 1) * 10
print('Матрица B: \n', B)

X1 = np.zeros(n)
X2 = np.zeros(n)
AM = np.column_stack((A, B[:, 0]))
AM_copy = np.column_stack((A, B[:, 0]))
print('Расширенная матрица А: \n', AM)

Матрица А: 
 [[7.16416141 2.24503723 0.55416516 5.62686267 1.8508988 ]
 [7.5210312  1.71027734 1.25643563 9.21027874 7.02646578]
 [9.65563191 8.00079416 1.2988792  7.94146067 7.72315498]
 [5.85059294 6.25919914 5.3714835  0.89321276 0.93563226]
 [3.95785402 2.08023331 2.50007877 2.72213647 0.51871582]]
Матрица B: 
 [[5.33576437]
 [8.1538501 ]
 [2.13357209]
 [4.14977455]
 [9.24961361]]
Расширенная матрица А: 
 [[7.16416141 2.24503723 0.55416516 5.62686267 1.8508988  5.33576437]
 [7.5210312  1.71027734 1.25643563 9.21027874 7.02646578 8.1538501 ]
 [9.65563191 8.00079416 1.2988792  7.94146067 7.72315498 2.13357209]
 [5.85059294 6.25919914 5.3714835  0.89321276 0.93563226 4.14977455]
 [3.95785402 2.08023331 2.50007877 2.72213647 0.51871582 9.24961361]]


Приведение к треугольному виду:

In [88]:
def triangle_form(expanded_matrix, mod):
  for i in range(n):
      if (expanded_matrix[i][i] == 0.0): 
          sys.exit('Divide by zero')

      if (mod==1): 
        if  expanded_matrix[i][i] != abs(max(expanded_matrix[i:, i])):
          index_line = np.argmax(abs(expanded_matrix[i:,i])) + i
          swap(expanded_matrix, index_line, i) 

      for j in range(i+1, n):
          main = expanded_matrix[j][i]/expanded_matrix[i][i]
          for k in range(n+1):
              expanded_matrix[j][k] = expanded_matrix[j][k] - main * expanded_matrix[i][k]
  #print(expanded_matrix)
  return expanded_matrix


Обратная подстановка:

In [89]:
def back_substitution(xi, matrix):
  xi[n-1] = matrix[n-1][n]/matrix[n-1][n-1]

  for i in range(n-2,-1,-1):
      xi[i] = matrix[i][n]
      
      for j in range(i+1,n):
          xi[i] = xi[i] - matrix[i][j]*xi[j]
      
      xi[i] = xi[i]/matrix[i][i]
  return xi

Функция перестановки строк:

In [59]:
def swap(matrix, index_from_line, index_to_line):
  line1, line2 = np.copy(matrix[index_from_line, :]), np.copy(matrix[index_to_line, :])
  matrix[index_to_line, :] = line1
  matrix[index_from_line, :] = line2
  return matrix

In [60]:
def solution(expanded_matrix, xi, mod):
  if (mod == 0):
    tr_m = triangle_form(expanded_matrix, 0)
  else:
    tr_m = triangle_form(expanded_matrix, 1)

  array = back_substitution(xi,tr_m)
  return array

**Расчет ошибки и невязки:**

In [103]:
def error(xi):
  #return np.sqrt(np.sum(np.power(abs(x_real-xi), 2)))
  return np.linalg.norm(x_real-xi)

def delta(xi):
  return np.linalg.norm(np.dot(A, xi) - B.T)

x_real = solve(A, B).reshape(1,n)
print('Истинное решение:  \n', x_real, '\n')

X_gauss = solution(AM, X1, 0)
X_gauss_mod =  solution(AM_copy, X2, 1)

print('Полученное решение методом Гаусса: \n', X_gauss, '\n Ошибка: \n', error(X_gauss), '\n Невязка:', delta(X_gauss),'\n')
print('Полученное решение улучшенным методом Гаусса: \n', X_gauss_mod, '\n Ошибка: \n', error(X_gauss_mod), '\n Невязка:', delta(X_gauss_mod),'\n')

Истинное решение:  
 [[-4.00228384  2.02596552  2.36539858  6.17616052 -3.56736132]] 

Полученное решение методом Гаусса: 
 [-4.00228384  2.02596552  2.36539858  6.17616052 -3.56736132] 
 Ошибка: 
 9.74975584715494e-15 
 Невязка: 2.6332655310265796e-14 

Полученное решение улучшенным методом Гаусса: 
 [-4.00228384  2.02596552  2.36539858  6.17616052 -3.56736132] 
 Ошибка: 
 5.924889052322839e-15 
 Невязка: 9.969778034532539e-15 

