<a href="https://colab.research.google.com/github/mainarel/Numerical_methods_7/blob/main/Lab1_Gauss_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Решение СЛАУ методом Гаусса**

Заполнение матрицы:

In [98]:
import numpy as np
import matplotlib.pyplot as plt
import sys
from scipy.linalg import solve

# размер матрицы А - n x n, B - n x 1
n = 5

#A = np.array([[1.0,10.0,6.0],[3.0,2.0,1.0],[4.0,10.0,6.0]])
#B = np.array([[3.0,19.0,7.0]]).reshape(n,1)
#A = np.random.randint(1, 100, (n, n))
A = np.random.rand(n, n) * 10
print('Матрица А: \n', A)


#B = np.random.randint(1, 100, (n, 1))
B = np.random.rand(n, 1) * 10
print('Матрица B: \n', B)

X1 = np.zeros(n)
X2 = np.zeros(n)
AM = np.column_stack((A, B[:, 0]))
AM_copy = np.column_stack((A, B[:, 0]))
print('Расширенная матрица А: \n', AM)

Матрица А: 
 [[0.3721239  4.65295589 0.26285482 0.32845339 4.59037547]
 [7.02182801 6.32269633 5.44071744 4.96518926 2.92397642]
 [9.82381337 9.38178307 8.31098819 8.69338434 2.72317656]
 [1.85301936 0.73645763 3.76148419 3.66811641 5.20683971]
 [5.21449354 3.21078301 8.05446604 7.42212635 8.59719394]]
Матрица B: 
 [[6.18459569]
 [0.46115072]
 [3.53703033]
 [3.57967632]
 [9.21390369]]
Расширенная матрица А: 
 [[0.3721239  4.65295589 0.26285482 0.32845339 4.59037547 6.18459569]
 [7.02182801 6.32269633 5.44071744 4.96518926 2.92397642 0.46115072]
 [9.82381337 9.38178307 8.31098819 8.69338434 2.72317656 3.53703033]
 [1.85301936 0.73645763 3.76148419 3.66811641 5.20683971 3.57967632]
 [5.21449354 3.21078301 8.05446604 7.42212635 8.59719394 9.21390369]]


Приведение к треугольному виду:

In [88]:
def triangle_form(expanded_matrix, mod):
  for i in range(n):
      if (expanded_matrix[i][i] == 0.0): 
          sys.exit('Divide by zero')

      if (mod==1): 
        if  expanded_matrix[i][i] != abs(max(expanded_matrix[i:, i])):
          index_line = np.argmax(abs(expanded_matrix[i:,i])) + i
          swap(expanded_matrix, index_line, i) 

      for j in range(i+1, n):
          main = expanded_matrix[j][i]/expanded_matrix[i][i]
          for k in range(n+1):
              expanded_matrix[j][k] = expanded_matrix[j][k] - main * expanded_matrix[i][k]
  #print(expanded_matrix)
  return expanded_matrix


Обратная подстановка:

In [89]:
def back_substitution(xi, matrix):
  xi[n-1] = matrix[n-1][n]/matrix[n-1][n-1]

  for i in range(n-2,-1,-1):
      xi[i] = matrix[i][n]
      
      for j in range(i+1,n):
          xi[i] = xi[i] - matrix[i][j]*xi[j]
      
      xi[i] = xi[i]/matrix[i][i]
  return xi

Функция перестановки строк:

In [59]:
def swap(matrix, index_from_line, index_to_line):
  line1, line2 = np.copy(matrix[index_from_line, :]), np.copy(matrix[index_to_line, :])
  matrix[index_to_line, :] = line1
  matrix[index_from_line, :] = line2
  return matrix

In [60]:
def solution(expanded_matrix, xi, mod):
  if (mod == 0):
    tr_m = triangle_form(expanded_matrix, 0)
  else:
    tr_m = triangle_form(expanded_matrix, 1)

  array = back_substitution(xi,tr_m)
  return array

**Расчет ошибки и невязки:**

In [99]:
def error(xi):
  #return np.sqrt(np.sum(np.power(abs(x_real-xi), 2)))
  return np.linalg.norm(x_real-xi)

def delta(xi):
  return np.linalg.norm(np.dot(A, xi) - B)

x_real = solve(A, B).reshape(1,n)
print('Истинное решение:  \n', x_real, '\n')


X_gauss = solution(AM, X1, 0)
X_gauss_mod =  solution(AM_copy, X2, 1)

print('Полученное решение методом Гаусса: \n', X_gauss, '\n Ошибка: \n', error(X_gauss), '\n Невязка:', delta(X_gauss),'\n')
print('Полученное решение улучшенным методом Гаусса: \n', X_gauss_mod, '\n Ошибка: \n', error(X_gauss_mod), '\n Невязка:', delta(X_gauss_mod),'\n')


print(np.linalg.norm(np.dot(A, X_gauss) - B))



Истинное решение:  
 [[-5.88483954  2.72268098  8.23240169 -3.3868556  -1.16450857]] 

Полученное решение методом Гаусса: 
 [-5.88483954  2.72268098  8.23240169 -3.3868556  -1.16450857] 
 Ошибка: 
 3.1680092908125005e-14 
 Невязка: 20.760534006735273 

Полученное решение улучшенным методом Гаусса: 
 [-5.88483954  2.72268098  8.23240169 -3.3868556  -1.16450857] 
 Ошибка: 
 6.423961869778975e-15 
 Невязка: 20.760534006735273 

20.760534006735273
